name: Copy README to januszpelc.github.io

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout StereoTool repository
      uses: actions/checkout@v3
      with:
        path: StereoTool

    - name: Checkout januszpelc.github.io repository
      uses: actions/checkout@v3
      with:
        repository: JanuszPelc/januszpelc.github.io
        path: januszpelc.github.io
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Copy README.md
      run: cp StereoTool/README.md januszpelc.github.io/README.md

    - name: Check for changes
      run: |
        cd januszpelc.github.io
        if git diff --quiet; then
          echo "No changes detected, skipping commit."
          exit 0
        else
          echo "Changes detected, proceeding to commit."
        fi

    - name: Commit and push changes
      if: success() && steps.check-for-changes.outputs.changed == 'true'
      run: |
        cd januszpelc.github.io
        git config --global user.email "87265669+JanuszPelc@users.noreply.github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README from StereoTool"
        git push
