name: Copy README to januszpelc.github.io

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  copy-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout StereoTool repository
      uses: actions/checkout@v3

    - name: Checkout januszpelc.github.io repository
      uses: actions/checkout@v3
      with:
        repository: JanuszPelc/januszpelc.github.io
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Copy README.md
      run: cp StereoTool/README.md januszpelc.github.io/README.md

    - name: Commit and push changes
      run: |
        cd januszpelc.github.io
        git config --global user.email "87265669+JanuszPelc@users.noreply.github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README from StereoTool"
        git push
